# Generated by Django 5.0.6 on 2024-06-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('amount', models.CharField(choices=[('$10', '$10'), ('$20', '$20'), ('$30', '$30'), ('$40', '$40'), ('$50', '$50'), ('$60', '$60'), ('$70', '$70'), ('$80', '$80')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
