# Generated by Django 5.1 on 2024-09-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_wallet_alter_donation_user_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
    ]
